config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'stats', to: 'pages#stats'
  get 'dashboard', to: 'pages#dashboard'
  get 'contact', to: 'pages#contact'
  resources :customers do
    resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:index, :show, :edit, :update, :destroy] do
    resources :products, only: [:new, :create]
  end
  resources :products, only: [:show ] do
    resources :feedbacks, only: [:edit, :update, :new, :create, :destroy]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='social-media'>
    <a href='https://github.com/Canakin' target='_blank'><i class='fab fa-github'></i></a>
    <a href='https://www.instagram.com/cancimenser/' target='_blank'><i class='fab fa-instagram'></i></a>
    <a href='https://twitter.com/Can_Cimenser' target='_blank'><i class='fab fa-twitter'></i></a>
    <a href='https://www.facebook.com/can.cimenser' target='_blank'><i class='fab fa-facebook'></i></a>
  </div>
  <div class='copyright'>
    <small><i>Created by Can Cimenser &#169</i></small>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/ds2odybte/image/upload/v1616062202/OT_yea2lh.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active" id='navLink'>
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item" id='navLink'>
          <%= link_to "Customers", customers_path, class: "nav-link"%>
        </li>
        <li class="nav-item" id='navLink'>
          <%= link_to "Orders", orders_path, class: "nav-link"%>
        </li>
        <li class="nav-item" id='navLink'>
          <%= link_to "Statistics", stats_path, class: "nav-link"%>
        </li>
        <li class="nav-item" id='navLink'>
          <%= link_to "Contacts", contact_path, class: "nav-link"%>
        </li>

        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else  %>
            <%= image_tag "https://toppng.com/uploads/preview/menu-icon-png-3-lines-11552739325vwldrdcxa3.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile Info",dashboard_path, class: "dropdown-item" %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>