config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'stats', to: 'pages#stats'
  get 'dashboard', to: 'pages#dashboard'
  get 'contact', to: 'pages#contact'
  resources :customers do
    resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:index, :show, :edit, :update, :destroy] do
    resources :products, only: [:new, :create]
  end
  resources :products, only: [:show ] do
    resources :feedbacks, only: [:edit, :update, :new, :create, :destroy]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  validates :company_name, presence: { strict: true }, uniqueness: true, length: { minimum: 3 }
  validates :contact_title, presence: true, length: { minimum: 6 }
  validates :address, presence: true, length: { minimum: 10, too_short: "Enter minimum %{count} characters" }
  validates :city, :country, presence: true, confirmation: { case_sensitive: false }
  validates :postal_code, presence: true, length: { minimum: 3 }
  validates :phone, presence: true, uniqueness: true
  validates :fax, :customer_id, presence: true
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :find_customer, only: [:show, :edit, :update, :destroy]
  def index
    searching
    set_marker
  end

  def show
    @order_list = @customer.orders
    if @order_list.blank?
      @orders = "Customer currently has no order"
    else
      @orders = @order_list
    end
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save!
      redirect_to customers_path
    else
      render "/customer/new"
    end
  end

  def edit; end

  def update
    if @customer.update!(customer_params)
      redirect_to customers_path
    else
      render 'customers/:id/edit'
    end
  end

  def destroy
    if @customer.orders.blank?
      @customer.destroy
      redirect_to customers_path
    else
      redirect_to customer_path(@customer), alert: "First delete the order, then you can delete the customer!!"
    end
  end

  private

  def find_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:company_name, :customer_id, :contact_title, :address, :city, :postal_code, :country, :phone, :fax)
  end

  def searching
    # Both searching and filtering method
    if params[:query].present?
      sql_query = " \
        customers.company_name @@ :query \
        OR customers.country @@ :query \
        OR customers.city @@ :query \
      "
      if params[:orders].present?
        @customers = []
        Customer.where(sql_query, query: "%#{params[:query]}%").each { |customer| customer.orders.exists? ? @customers << customer : @customers }
      else
        @customers = Customer.where(sql_query, query: "%#{params[:query]}%")
      end
    else
      @customers = Customer.all
    end
  end

  def set_marker
    # Settings markers list consisting of coordinates of cities that our customer is located
    @markers = []
    @customers.each { |customer| @markers << { lat: customer.latitude, lng: customer.longitude } }
  end
end

app/views/customers/edit.html.erb
<div class='container'>
  <div class='card-body'>
    <div class='form_style'>
      <h2>Edit <%= @customer.company_name %> Info</h2>
      <hr>
      <%= simple_form_for @customer do |f| %>
        <%= f.input :company_name, label: "Company Name" %>
        <%= f.input :address, label:"Address" %>
        <%= f.input :contact_title, label:'Contact Title' %>
        <%= f.input :city, label:'City' %>
        <%= f.input :postal_code, label:'Postal Code' %>
        <%= f.input :country, label:"Country" %>
        <%= f.input :phone, label:'Phone' %>
        <%= f.input :fax, label:'Fax'%>
        <%= f.input :customer_id, label:'Customer ID' %>
        <%= f.submit %>
      <% end %>
    </div>
    <%= link_to 'Back to customers', customers_path, class:'btn btn-secondary', id:'btn_center' %>
  </div>
</div>

app/views/customers/index.html.erb
<div class='container'>
  <br>
  <h1>Customers</h1>
  <hr>
  <div class='card-body'>
    <h3>Search & Filter </h3>
    <%= form_tag customers_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a customer by company name, country or city"
      %>
      <br>
      <%= label_tag "orders", "Click for customers with orders" %>
      <%= check_box_tag :orders%>
      <br>
      <br>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
    <br>
    <div id='customerButtons'>
      <%= link_to "Clear Search Options", customers_path, class:'btn btn-primary' %>
      <%= link_to "Add New Customer", new_customer_path, class:'btn btn-secondary' %>
      <%= link_to "Go to Map", "#map", class:'btn btn-success' %>
    </div>
    <hr>
  </div>
  <div id='customersAll'>
    <% @customers.each do |customer| %>
    <div class='card' id='customer_card'>
      <%= link_to customer_path(customer) do %>
      <h4><%= customer.company_name %></h4>
      <% end %>
      <p><b>Address:</b> <%= customer.address %></p>
      <p><b>Country:</b> <%= customer.country %></p>
      <p><b>City:</b> <%= customer.city %></p>
    </div>
    <% end %>
  </div>
  <h3>Address of the Customer</h3>
  <div id="map"
    style="width: 100%; height: 600px;"
    data-markers="<%= @markers.to_json %>">
  </div>
  <button onclick='goToTop()' id='myBtn' title='Go to top'>Top</button>
</div>

<script type='text/javascript'>
  const topbutton = document.getElementById('myBtn');
  const selection = document.getElementById('filter');
  const customerAll = document.getElementById('customersAll');

  window.onscroll = function() {scrollFunction()}
  const scrollFunction = () => {
    if (document.body.scrollTop > 30 || document.documentElement.scrollTop > 30) {
      topbutton.style.display = "block";
    } else {
      topbutton.style.display = "none";
    }
  }

  const goToTop = () => {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
</script>

app/views/customers/new.html.erb
<div class='container'>
  <div class='card-body'>
    <div class='form_style'>
      <h2>Add new customer <i class="fas fa-user-plus"></i></h2>
      <hr>
        <%= simple_form_for @customer do |f| %>
          <%= f.input :company_name, label: "Company Name" %>
          <%= f.input :address, label:"Address" %>
          <%= f.input :contact_title, label:'Contact Title' %>
          <%= f.input :city, label:'City' %>
          <%= f.input :postal_code, label:'Postal Code' %>
          <%= f.input :country, label:"Country" %>
          <%= f.input :phone, label:'Phone' %>
          <%= f.input :fax, label:'Fax'%>
          <%= f.input :customer_id, label:'Customer ID' %>
          <%= f.submit %>
        <% end %>
    </div>
    <%= link_to 'Back to customers', customers_path, class:'btn btn-secondary', id:'btn_center' %>
  </div>
</div>

app/views/customers/show.html.erb
<div class='container'>
  <div class='card-body' id='orderDetail'>
    <h2><%= @customer.company_name %></h2>
    <hr>
    <p align='center'><b>Contact Title:</b> <%= @customer.contact_title %></p>
    <p align='center'><b>Address:</b> <%= @customer.address %></p>
    <p align='center'><b>City: </b><%= @customer.city %></p>
    <p align='center'><b>Postal Code:</b> <%= @customer.postal_code %></p>
    <p align='center'><b>Country:</b> <%= @customer.country %></p>
    <p align='center'><b>Phone:</b> <%= @customer.phone %></p>
    <p align='center'><b>Fax:</b> <%= @customer.fax %></p>
    <div>
    <h3>Customer Orders </h3>
    <hr>
    <% if @orders.kind_of?(String) %>
      <p align='center'><%= @orders %></p>
    <% else  %>
      <% @orders.each do |order|  %>
        <p align='center'><b>Order ID:</b> <%= order.orderid %></p>
        <p align='center'><b>Order Employee ID:</b> <%= order.employee_id  %><p>
        <%= link_to "See order details",order_path(order), class:'btn btn-secondary', id:'btn_center' %>
        <hr>
      <% end %>
    <% end %>
    <%= link_to 'Add new order', new_customer_order_path(@customer), class:'btn btn-secondary', id:'btn_center' %>
    </div>
    <div id='customerButtons'>
      <%= link_to "See all Customers", customers_path, class:'btn btn-primary' %>
      <%= link_to "Edit Customer", edit_customer_path, class:'btn btn-secondary' %>
      <%= link_to "Delete Customer", customer_path, method: :delete, data: { confirm: 'Are you sure you want to delete the customer?'}, class:'btn btn-danger'%>
    </div>
  </div>
</div>