config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'stats', to: 'pages#stats'
  get 'dashboard', to: 'pages#dashboard'
  get 'contact', to: 'pages#contact'
  resources :customers do
    resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:index, :show, :edit, :update, :destroy] do
    resources :products, only: [:new, :create]
  end
  resources :products, only: [:show ] do
    resources :feedbacks, only: [:edit, :update, :new, :create, :destroy]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :products
  validates :employee_id, presence: true, numericality: { only_integer: true }
  validates :order_date, :require_date, :ship_postal_code, :ship_name, presence: true
  validates :ship_via, presence: true, numericality: { only_integer: true }
  validates :ship_adress, presence: true, length: { minimum: 10, too_short: "Enter minimum %{count} characters" }
  validates :ship_city, :shio_country, presence: true, confirmation: { case_sensitive: false }
  validates :orderid, :freight, presence: true, numericality: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, only: [:show, :edit, :update, :destroy]
  def index
    searching
  end

  def show; end

  def new
    @order = Order.new
  end

  def create
    @customer = Customer.find(params[:customer_id])
    @order = Order.new(order_params)
    @order.customer = @customer
    if @order.save!
      redirect_to orders_path
    else
      render new_order_path
    end
  end

  def edit; end

  def update
    if @order.update!(order_params)
      redirect_to orders_path
    else
      render edit_order_path
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_path
  end

  private

  def searching
    # both searching and filterin results method
    if params[:query].present?
      sql_query = "\
        employee_id @@ :query \
        OR shio_country @@ :query \
        OR ship_city @@ :query \
        OR ship_postal_code @@ :query \
        OR ship_name @@ :query \
        "
      if params[:products].present?
        @orders = []
        Order.where(sql_query, query: "%#{params[:query]}%").each { |order| order.products.count > 1 ? @orders << order : @orders }
      else
        @orders = Order.where(sql_query, query: "%#{params[:query]}%")
      end
    else
      @orders = Order.all
    end
  end

  def find_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:employee_id, :order_date, :require_date, :ship_via, :freight, :ship_name, :ship_adress, :ship_city, :ship_postal_code, :shio_country, :orderid, :customer_id)
  end
end

app/views/orders/edit.html.erb
<div class='container'>
  <div class='card-body'>
    <div class='form_style'>
      <h2>Add new order <i class="fas fa-user-plus"></i></h2>
      <hr>
        <%= simple_form_for @order do |f| %>
          <%= f.input :employee_id, label: "Employee ID" %>
          <%= f.input :order_date, label:"Order Date" %>
          <%= f.input :require_date, label:'Require Date' %>
          <%= f.input :ship_via, label:'Ship Via', hint:'Enter an integer!' %>
          <%= f.input :freight, label:'Freight' %>
          <%= f.input :ship_name, label:"Ship Name" %>
          <%= f.input :ship_adress, label:'Ship Address' %>
          <%= f.input :ship_city, label:'Ship City'%>
          <%= f.input :ship_postal_code, label:'Ship Postal Code' %>
          <%= f.input :shio_country, label:'Ship Country' %>
          <%= f.input :customer_id, as: :integer, label:'Customer ID' %>
          <%= f.submit %>
        <% end %>
    </div>
    <%= link_to 'Back to orders', orders_path, class:'btn btn-secondary', id:'btn_center' %>
  </div>
</div>

app/views/orders/index.html.erb
<div class='container'>
  <br>
  <h1>Orders</h1>
  <hr>
  <div class='card-body'>
    <h3>Search & Filter </h3>
    <%= form_for orders_path, method: :get do |form| %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a order by company name, country, city or employee ID"
      %>
      <br>
      <%= label_tag "products", "Click for orders with more than one products" %>
      <%= check_box_tag :products%>
      <br>
      <br>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
    <br>
    <div id='customerButtons'>
      <%= link_to "Clear Search Options", orders_path, class:'btn btn-primary' %>
    </div>
    <hr>
  </div>
  <div id='orderAll'>
    <% @orders.each do |order| %>
    <div class='card' id='customer_card'>
    <%= link_to order_path(order) do %>
      <h2><%= "Order #{order.orderid}" %></h2>
    <% end %>
      <p><b>Employee Id:</b> <%= order.employee_id %></p>
      <p><b>Order Freight:</b> <%= order.freight %></p>
      <p><b>Order Customer:</b> <%= order.customer.company_name %></p>
      <p><b>Ship Country:</b> <%= order.shio_country %></p>
      <p><b>Ship City:</b> <%= order.ship_city %></p>
      <hr>
    </div>
    <% end %>
  </div>
  <button onclick='goToTop()' id='myBtn' title='Go to top'>Top</button>
</div>

app/views/orders/new.html.erb
<div class='container'>
  <div class='card-body'>
    <div class='form_style'>
      <h2>Add new order <i class="fas fa-user-plus"></i></h2>
      <hr>
        <%= simple_form_for [:customer_id, @order], url:customer_orders_path(params[:customer_id]) do |f| %>
          <%= f.input :employee_id, label: "Employee ID" %>
          <%= f.input :order_date, as: :date %>
          <%= f.input :require_date, as: :date %>
          <%= f.input :ship_via, label:'Ship Via', hint:'Enter an integer!' %>
          <%= f.input :freight, label:'Freight' %>
          <%= f.input :ship_name, label:"Ship Name" %>
          <%= f.input :ship_adress, label:'Ship Address' %>
          <%= f.input :ship_city, label:'Ship City'%>
          <%= f.input :ship_postal_code, label:'Ship Postal Code' %>
          <%= f.input :shio_country, label:'Ship Country' %>
          <%= f.input :orderid, as: :integer, label:'Order ID' %>
          <%= f.submit %>
        <% end %>
    </div>
    <%= link_to 'Back to orders', orders_path, class:'btn btn-secondary', id:'btn_center' %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class='row' id='orderBox'>
    <div class='col-sm'>
      <h2><%= "Order #{@order.orderid}" %></h2>
      <hr>
      <p><b>Order Employee  Id: </b> <%= @order.employee_id %></p>
      <p><b>Order Ship Via: </b> <%= @order.ship_via %></p>
      <p><b>Order Freight:</b> <%= @order.freight %> $</p>
      <p><b>Order Ship Name:</b> <%= @order.ship_name %></p>
      <p><b>Order Ship Address:</b> <%= @order.ship_adress %></p>
      <p><b>Order Ship City:</b> <%= @order.ship_city %></p>
      <p><b>Order Ship Postal Code:</b> <%= @order.ship_postal_code %></p>
      <div style='margin-bottom: 20px'>
        <%= link_to "See All Orders", orders_path, class:"btn btn-primary" %>
        <br>
        <br>
         <%= link_to "Edit Order", edit_order_path(@order), class:'btn btn-secondary' %>
      </div>
      <div id='orderImage'>
        <%= image_tag "https://images.unsplash.com/photo-1578575437130-527eed3abbec?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80", width:"300px", height:"200px" %>
      </div>
    </div>
   </div>
   <div class="col-sm">
      <% if @order.products.exists? %>
        <table>
          <tbody>
            <tr>
              <th colspan="4"><h2>Products</h2></th>
            </tr>
            <tr>
              <% @order.products.each do |product| %>
              <td><h4>Product <%= product.productid %></h4></td>
              <td><p><b>Product Price:</b> <%= product.unit_price %> $</p></td>
              <td><p><b>Product Quantity:</b> <%= product.quantity %></p></td>
              <td><%= link_to "See product details", product_path(product) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>You need to add product</p>
      <% end %>
        <br>
        <%= link_to 'Add new product', new_order_product_path(@order), class:'btn btn-secondary', id:'btn_center' %>
    </div>
</div>