config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'stats', to: 'pages#stats'
  get 'dashboard', to: 'pages#dashboard'
  get 'contact', to: 'pages#contact'
  resources :customers do
    resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:index, :show, :edit, :update, :destroy] do
    resources :products, only: [:new, :create]
  end
  resources :products, only: [:show ] do
    resources :feedbacks, only: [:edit, :update, :new, :create, :destroy]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :order
  has_many :feedbacks, dependent: :destroy
  validates :quantity, :productid, presence: true, numericality: { only_integer: true }
  validates :discount, presence: true, numericality: { less_than_or_equal_to: 1 }
  validates :unit_price, presence: true, numericality: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @order = Order.find(params[:order_id])
    @product = Product.new(product_params)
    @product.order = @order
    if @product.save!
      redirect_to order_path(@order)
    else
      render new_product_path
    end
  end

  private

  def product_params
    params.require(:product).permit(:productid, :unit_price, :quantity, :discount, :order_id)
  end
end

app/views/products/new.html.erb
<div class='container'>
  <div class='card-body'>
    <div class='form_style'>
      <h2>Add new product <i class="fas fa-user-plus"></i></h2>
      <hr>
        <%= simple_form_for [:order_id, @product], url: order_products_path(params[:order_id]) do |f| %>
          <%= f.input :productid, label: "Product ID" %>
          <%= f.input :unit_price, as: :float, label:'Unit Price' %>
          <%= f.input :quantity, as: :integer, label:'Quantity' %>
          <%= f.input :discount, input_html: { step: 0.01 }, label:'Discount', hint:'Enter an percentage!' %>
          <%= f.submit %>
        <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class='container'>
  <div class='col-lg-'>
    <h1>Product Details</h1>
    <hr>
    <div id='productDetails'>
      <h3>Product ID: <%= @product.productid %></h3>
      <p><b>Product Price:</b> <%= @product.unit_price %> $</p>
      <p><b>Product Quantity:</b> <%= @product.quantity %> units</p>
      <p><b>Product Discount:</b> <%= @product.discount * 100 %>%</p>
    </div>
    <hr>
    <h4 align='center'>Feedbacks</h4>
    <% @product.feedbacks.each do |feedback| %>
    <div id='feedback'>
      <% if feedback.present? %>
        <p><b>Nickname: </b> <%= feedback.user.nickname %></p>
        <p><b>Title: </b><%= feedback.title %></p>
        <p><b>Content: </b><%= feedback.content %></p>
        <% if feedback.user == current_user %>
          <%= link_to product_feedback_path(@product, feedback), method: :delete, data: { confirm: 'Are you sure you want to delete your feedback?'} do %>
            <i class="fa fa-trash destroy_feedback"></i>
          <% end  %>
          <%= link_to edit_product_feedback_path(@product, feedback) do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      <% else %>
        <p><%= "Currently has no feedback!" %></p>
      <% end %>
    <% end %>
    </div>
    <%= link_to "Share your feedback", new_product_feedback_path(@product), class:"btn btn-secondary", id:'btn_center' %>
  </div>
</div>